noun1=input("Tell me a noun.")
animal1=input("Tell me an animal.")
verb1=input("Give me a verb.")
verb2=input("Give me another verb.")
adj1=input("Please tell me an adjective.")
vehicle=input("Give me a name of a vehicle/means of transportation. *Anything*")
belonging=input("Give me an object.")
num1=input("Tell me a number.")
num2=input("Tell me another number.")
print("                                                                         ")
print("~*~*~*~*~*~*~*~*~*~*~*~*~-The Family Picnic-~*~*~*~*~*~**~*~*~*~*~*~*~*~*")
print("                                                                         ")
print("Today we were going on a family picnic. I was really hyped because I haven't been on a picnic in "+num1+" days!")
print("I was in my room when my mom called to get ready, and to bring a "+belonging+" with me. Just in case.")
print("I quickly ran downstairs with the "+belonging+" and got on the "+vehicle+".")
print("I was really"+adj1+" to meet all my relatives. I had a whopping "+num2+" aunts and uncles.")
print("When we got to the picnic area, I saw a wild "+animal1+". Yeah! Really! A wild "+animal1+"!")
print("We sat down on our towels, and my mom took out some delicous "+noun1+" sandwiches!")
print("There was a lot of mmmming and "+verb1+" so when it was time to go we were all sad.")
print("That was our family picnic!")
print("                                                 ")
print("*~*~*~*~*~*~*~*~*~*~*~THE END~*~*~*~*~*~*~*~*~*~*~~*~*")
